name: 步步宝
on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 0-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BBB_bububaoTOKEN: ${{ secrets.BBB_bububaoTOKEN }}
        BBB_CASH: ${{ secrets.BBB_CASH }}   
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【步步宝】'
        if: env.BBB_bububaoTOKEN 
        run: |
          node Script/bububao.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
