# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node	

name: 中青浏览赚	

on:	
  workflow_dispatch:	
  schedule:	
     - cron: '5 1 * * *'	
  watch:	
    types: started	
jobs:	
  build:	
    runs-on: ubuntu-latest	
    if: github.event.repository.owner.id == github.event.sender.id	
    env:	
      YOUTH_BANNER: ${{ secrets.YOUTH_BANNER }}		
      TZ: Asia/shanghai	
    steps:	
      - name: Checkout	
        uses: actions/checkout@v1	
      - name: Use Node.js 14.x	
        uses: actions/setup-node@v1	
        with:	
          node-version: 14.x	
      - name: npm install	
        run: |	
          npm install	
          	
      - name: '运行 【中青浏览赚】'	
        if: env.YOUTH_BANNER
        run: |	
          node Script/youth_banner.js	
        env:	
         YOUTH_BANNER: ${{ secrets.YOUTH_BANNER }}	 
        
